CREATE SCHEMA IF NOT EXISTS auth;

CREATE SCHEMA IF NOT EXISTS users;

CREATE SCHEMA IF NOT EXISTS songs;

CREATE SCHEMA IF NOT EXISTS playlists;

CREATE SCHEMA IF NOT EXISTS streaming;

CREATE SCHEMA IF NOT EXISTS analytics;